security_groups:
  - name: test-sg-01 
    vpc: VPC-SGP-TST-C-001
    ingress:
      - name: allow-inbound
        mode: cidr
        source:
          - "0.0.0.0" 
        rules:
          - ssh-tcp
    egress:
      - name: allow-outbound 
        target: anywhere
        rules:
          - all-all
