aws_ip_ranges:
  excluding_services:
  - EC2
  - S3
  - DYNAMODB
  request_headers:
    Accept: application/json
  request_url: https://ip-ranges.amazonaws.com/ip-ranges.json
security_groups:
  - name: test-sg-01
    vpc: VPC-SGP-TST-C-001
    ingress:
      - name: allow-inbound
        mode: cidr
        source:
          - "0.0.0.0" 
        rules:
          - ssh-tcp
    egress:
      - name: allow-outbound 
        target: anywhere
        rules:
          - all-all
