opensearch: []
  # - domain_name: maersk-opensearch-test
  #   advanced_security_options_internal_user_database_enabled: true
  #   master_user_name: galvin-test
  #   security_group_ids:
  #     - sg-061727e38f00628f3
  #   subnet_ids:
  #     - subnet-05ef56d517ea09416
  #     - subnet-0874b307cb93c32da