s3_buckets:  
  - name: 129980683758-test-bucket-demo
    tags:
      test: test
      test2: test2
    enable_versioning: true
    lifecycle_rules:
      - id: abort_incomplete_multipart_upload
        status: Enabled 
        abort_incomplete_multipart_upload:
          days_after_initiation: 7
      - id: storage_class_transition
        status: Enabled 
        transition:
          - days: 30
            storage_class: STANDARD_IA
          - days: 60
            storage_class: GLACIER
          - days: 150
            storage_class: DEEP_ARCHIVE
      - id: current_version_expiration
        status: Enabled 
        expiration:
          - days: 365
      - id: noncurrent_version_storage_class_transition
        status: Enabled 
        noncurrent_version_transition:
          - noncurrent_days: 30 
            storage_class: STANDARD_IA
          - noncurrent_days: 60
            storage_class: GLACIER
          - noncurrent_days: 150
            storage_class: DEEP_ARCHIVE
      - id: noncurrent_version_expiration
        noncurrent_version_expiration:
          - newer_noncurrent_versions: 3
            noncurrent_days: 30
    tiering_configuration:
      - name: Test-tiering
        filter:
          prefix: "documents/"
          tags:
            priority: high
            class: blue
        tiering:
          - access_tier: "ARCHIVE_ACCESS"
            days: 125
          - access_tier: "DEEP_ARCHIVE_ACCESS"
            days: 180
    access_logs:
      enabled: true
      target_bucket: 129980683758-test-bucket-demo
      target_prefix: test
      target_object_key_format:
        partitioned_prefix:
          partition_date_source: DeliveryTime
    policies:
      statement:
      - sid: AWSConsoleStmt-1669628968037
        effect: Allow
        principals:
          - type: AWS
            identifiers:
              - arn:aws:iam::114774131450:root
        actions: 
          - s3:PutObject
        resources: 
          - arn:aws:s3:::129980683758-test-bucket-demo
          - arn:aws:s3:::129980683758-test-bucket-demo/*
      # - sid: AWSLogDeliveryWrite
      #   effect: Allow
      #   principals:
      #     - type: Service
      #       identifiers:
      #         - delivery.logs.amazonaws.com
      #   actions: 
      #     - s3:PutObject
      #   resources: 
      #     - arn:aws:s3:::405435454034-elb/AWSLogs/405435454034/*
      #   condition:
      #     - test: StringEquals
      #       variable: s3:x-amz-acl
      #       values:
      #         - bucket-owner-full-control
      # - sid: AWSLogDeliveryAclCheck
      #   effect: Allow
      #   principals:
      #     - type: Service
      #       identifiers:
      #         - delivery.logs.amazonaws.com
      #   actions: 
      #     - s3:GetBucketAcl
      #   resources: 
      #     - arn:aws:s3:::405435454034-elb
