aws_ip_ranges:
  excluding_services:
    - EC2
    - S3
    - DYNAMODB
  request_headers:
    Accept: application/json
  request_url: https://ip-ranges.amazonaws.com/ip-ranges.json

cidr_block_groups:
  - cidr_blocks:
      - 0.0.0.0/0
    name: anywhere

rules:
  - description: Allow jumphost ssh
    from_port: 22
    name: ssh
    protocol: tcp
    to_port: 22
  - description: Allow jumphost rdp
    from_port: 3389
    name: rdp
    protocol: tcp
    to_port: 3389
  - description: Allow intra ping
    from_port: -1
    name: ICMP
    protocol: icmp
    to_port: -1
  - description: Allow MYSQL/Aurora
    from_port: 3306
    name: MYSQL/Aurora
    protocol: tcp
    to_port: 3306
  - description: Allow PostgreSQL
    from_port: 5432
    name: PostgreSQL
    protocol: tcp
    to_port: 5432
  - name: zabbix-agent
    protocol: tcp
    from_port: 10051
    to_port: 10051
    description: Allow access from Zabbix agents
  - name: from-zabbix-server
    protocol: tcp
    from_port: 10050
    to_port: 10050
    description: Allow access from Zabbix servers

rule_groups:
  - name: jumphost-sg
    rules:
      - ssh
      - rdp

security_groups:  
  # - name: test-sg
  #   vpc: VPC-SGP-TST-C-001
  #   ingress:
  #     - name: allow-inbound
  #       mode: cidr
  #       source:
  #         - "0.0.0.0/0"
  #       rules:
  #         - ssh
  #   egress:
  #     - name: allow-outbound
  #       target: anywhere
  #       rules:
  #         - all-all
  # - name: test-galvin-02
  #   vpc: VPC-SGP-TST-C-001
  #   ingress:
  #     - name: allow-inbound
  #       mode: cidr
  #       source:
  #         - "0.0.0.0/0"
  #       rules:
  #         - rdp
  #   egress:
  #     - name: allow-outbound
  #       target: anywhere
  #       rules:
  #         - all-all
  - name: sgZabbixAgent
    vpc: Eric-Test-VPC-2
    ingress:
      - name: zabbix-server-inbound
        mode: sg
        source:
          - sgZabbixServer
        rules:
          - from-zabbix-server 
    egress:
      - name: to-zabbix-server
        mode: sg
        target: 
          - sgZabbixServer
        rules:
          - zabbix-agent
  - name: sgZabbixServer
    vpc: Eric-Test-VPC-2
    ingress:
      - name: zabbix-agent-inbound
        mode: sg
        source: 
          - sgZabbixServer
        rules:
          - zabbix-agent
      - name: zabbix-ui-access
        mode: cidr
        source:
          - anywhere
        rules:
          - https-443-tcp
    egress:
      - name: allow-outbound
        target: 
          - anywhere
        rules:
          - all-all
