ec2_instances: 
  - name: test-host 
    ami: ami-0896ef7bec0d0e792
    subnet: test-eip
    security_groups:
      - default
    instance_type: t3.small
    iam_instance_profile: EC2-test-role 
    eip: VPC-SGP-TST-C-1-ap-southeast-1a
    root_block_device:
      volume_type: gp3 
      volume_size: 20
    volume_groups:
      - name: sdf 
        type: io1 
        size: 50
        iops: 1000 
    user_data_ssm: true
    user_data: | 
      runcmd:
        - amazon-linux-extras install -y python3.8
        - yum install -y wheel
    source_dest_check: false
    tags:
      test-tag: little kitty eat 2 cookies

