vpcs: 
  - name: VPC-SGP-TST-C-1
    cidr: 172.18.76.0/25
    secondary_cidr_blocks:
      - 172.18.76.128/26
    azs:
      - ap-southeast-1a
      - ap-southeast-1b
    private_subnets:
      - 172.18.76.0/26
      - 172.18.76.64/26
    private_subnet_tags:
      - Name: SN-SGP-TST-PRT-AP01-AZA
        kubernetes.io/role/internal-elb: 1
        test: test
      - Name: SN-SGP-TST-PRT-AP01-AZB
        kubernetes.io/role/internal-elb: 1
    private_route_table_tags:
      - Name: RTB-SGP-TST-PRT-AP01-ALL
    public_subnets:
      - 172.18.76.128/28
      - 172.18.76.144/28
    public_subnet_tags:
      - Name: SN-SGP-TST-PRT-public-AZA
      - Name: SN-SGP-TST-PRT-public-AZB
    public_route_table_tags:
      - Name: RTB-SGP-TST-PRT-public-ALL
    public_dedicated_network_acl: true
    enable_s3_endpoint: true
    enable_dynamodb_endpoint: true
    enable_nat_gateway: true 
    single_nat_gateway: true
    enable_dhcp_options: true
    dhcp_options_ntp_servers: [ 169.254.169.123 ]