vpcs: 
  - name: VPC-SGP-TST-C-1
    cidr: 172.18.76.0/25
    secondary_cidr_blocks:
      - 172.18.76.128/26
    azs:
      - ap-southeast-1a
      - ap-southeast-1b
    private_subnets:
      - 172.18.76.0/26
      - 172.18.76.64/26
    private_subnet_tags:
      - Name: SN-SGP-TST-PRT-AP01-AZA
        kubernetes.io/role/internal-elb: 1
        test: test
      - Name: SN-SGP-TST-PRT-AP01-AZB
        kubernetes.io/role/internal-elb: 1
    private_route_table_tags:
      - Name: RTB-SGP-TST-PRT-AP01-ALL
    public_subnets:
      - 172.18.76.128/28
      - 172.18.76.144/28
    public_subnet_tags:
      - Name: SN-SGP-TST-PRT-public-AZA
      - Name: SN-SGP-TST-PRT-public-AZB
    public_route_table_tags:
      - Name: RTB-SGP-TST-PRT-public-ALL
    public_dedicated_network_acl: true
    enable_s3_endpoint: true
    enable_dynamodb_endpoint: true
    enable_nat_gateway: true 
    single_nat_gateway: true
    enable_dhcp_options: true
    dhcp_options_ntp_servers: [ 169.254.169.123 ]
    enable_flow_log: true
    flow_log_destination_type: s3
    flow_log_destination_arn: a-drift-remediation-test-s3-129980683758
    flow_log_traffic_type: ALL
    vpc_flow_log_tags:
      test: test

  - name: Eric-Test-VPC-2
    cidr: 172.17.0.0/16
    enable_dns_hostnames: true
    enable_dns_support: true
    tags:
      Account: Lab
      Environment: Sandbox

    # DHCP
    enable_dhcp_options: true
    dhcp_options_ntp_servers: [169.254.169.123, 10.10.10.10]
    dhcp_options_domain_name: abc.example.com
    dhcp_options_domain_name_servers: [10.0.0.1, 10.0.0.2]

    # Subnets
    azs:
      - ap-southeast-1a
      - ap-southeast-1b

    # Private subnets
    private_subnets:
      - 172.17.0.0/19
      - 172.17.32.0/19
    private_subnet_tags:
      - Name: Eric-Test-VPC-Private-a
        Account: Lab
        Environment: Sandbox
      - Name: Eric-Test-VPC-Private-b
        Account: Lab
        Environment: Sandbox
    private_route_table_tags:
      - Name: Eric-Test-VPC-Private-RT-a
      - Name: Eric-Test-VPC-Private-RT-b

    # NAT, private subnets must be integrated with NAT settings
    enable_nat_gateway: true

# #     ### 1. single_nat_gateway: one Nat for all private subnets in this VPC
# #     # single_nat_gateway: true

# #     ### 2. if there is no nat parameters, One NAT Gateway per subnet (default behavior)

    ### 3. One NAT Gateway per availability zone
    one_nat_gateway_per_az: true

    nat_gateway_tags:
      Account: Lab
      Environment: Sandbox

    # Intra subnets
    intra_subnets:
      - 172.17.64.0/19
      - 172.17.96.0/19
    intra_subnet_tags:
      - Name: Eric-Test-VPC-Intra-a
        Account: Lab
        Environment: Sandbox
      - Name: Eric-Test-VPC-Intra-b
        Account: Lab
        Environment: Sandbox
    intra_route_table_tags:
      - Name: Eric-Test-VPC-Intra-RT

    # TGW subnets
    tgw_subnets:
      - 172.17.128.0/19
      - 172.17.160.0/19
    tgw_subnet_tags:
      - Name: Eric-Test-VPC-TGW-a
        Account: Lab
        Environment: Sandbox
      - Name: Eric-Test-VPC-TGW-b
        Account: Lab
        Environment: Sandbox
    tgw_route_table_tags:
      - Name: Eric-Test-VPC-TGW-RT
    tgw_dedicated_network_acl: true

    # Public subnets
    public_subnets:
      - 172.17.192.0/19
      - 172.17.224.0/19
    public_subnet_tags:
      - Name: Eric-Test-VPC-Public-a
        Account: Lab
        Environment: Sandbox
      - Name: Eric-Test-VPC-Public-b
        Account: Lab
        Environment: Sandbox
    public_route_table_tags:
      - Name: Eric-Test-VPC-PUBLIC-RT