lbs: 
  - name: alb-test
    load_balancer_type: application
    internal: true
    ip_address_type: null
    vpc: VPC-SGP-TST-C-1
    security_groups:
      - default
    subnet_mapping:
      - subnet: SN-SGP-TST-PRT-AP01-AZA
      - subnet: SN-SGP-TST-PRT-AP01-AZB
    http_tcp_listeners:
      - port: 8080
        protocol: HTTP 
        target_group_name: prdapp
    http_tcp_listener_rules:
      - name: lst-rule-1
        priority: 100
        http_tcp_listener_port: 8080
        actions:
          # - type: redirect
          #   host: www.test.com.sg
          #   path: /
          #   port: 80
          #   protocol: HTTP
          #   status_code: HTTP_301
          - type: forward
            target_group_name: prdapp
        conditions:
          - path_patterns: 
              - /forward/*
        tags:
          test: test2
      - name: lst-rule-2 
        priority: 101
        http_tcp_listener_port: 8080
        actions:
          - type: redirect
            host: www.test.com.sg
            path: /
            port: 80
            protocol: HTTP
            status_code: HTTP_301
        conditions:
          - path_patterns: 
            - /redirect/*
    enable_deletion_protection: false
    #    access_logs:
    #      enabled: true
    #      bucket: <test-lb-accesslog-logging-123456789012>
    target_groups:
      - name: prdapp 
        backend_protocol: HTTP
        backend_port: 8080
        target_type : instance 
        preserve_client_ip: false
        stickiness:
          type: lb_cookie
          enabled: true
        connection_termination: true
        health_check:
          protocol: HTTP
          path: /php/login.php
          port: 8080 
          interval: 10
          healthy_threshold: 3
          unhealthy_threshold: 3
          timeout: 5
          matcher: 200-399
    attachments:
      - name: tst-ath-0
        target_group_name: prdapp
        target:
          - test-host
          - test-host2
        port: 8080
