ebs_volumes: 
  # - name: ansible-testhost5/sdg
  #   availability_zone: ap-southeast-1a
  #   type: gp3
  #   size: 40
  #   attachment:
  #     instance_name: ansible-testhost5
  #     device_name: sdg