ebs_volumes: 
  - name: test-host/sdg
    availability_zone: ap-southeast-1a
    type: gp3
    size: 40
    # type: io1
    # size: 50
    iops: 1000
  #   attachment:
  #     instance_name: test-host
  #     device_name: sdg
  - name: test-host/sdf
    availability_zone: ap-southeast-1a
    type: gp3
    size: 40
    # type: io1
    # size: 50
    iops: 1000
  - name: test-host/sdh
    availability_zone: ap-southeast-1a
    type: gp3
    size: 8
    # size: 50
    # iops: 1000
