---
  name: demo workflow 
  on:
    workflow_dispatch:
    pull_request:
      paths:
        - demo/demo-account/demo-application/**
        - .github/workflows/terraform-demo.yml
    push:
      paths:
        - demo/demo-account/demo-application/**
        - .github/workflows/terraform-demo.yml
     
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
  jobs:
    preparation:
      name: preparation
      runs-on: ubuntu-latest
      outputs: 
        network: ${{ steps.filter.outputs.network }}
        resources: ${{ steps.filter.outputs.resources }}
        changes: ${{ steps.filter.output.changes }}
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Change filter
          uses: dorny/paths-filter@v2
          id: filter
          with:
             filters: |
                network:
                  - 'demo/demo-account/demo-application/network/**'
                resources:
                  - 'demo/demo-account/demo-application/resources/**'

    terraform:
      needs: preparation
      uses: ./.github/workflows/reusable-terraform-workflow.yaml
      strategy:
        matrix: 
          subdirectories: ${{ needs.preparation.outputs.changes }}
        max-parallel: 1
      with:
        path: demo/demo-account/demo-application/${{ matrix.subdirectories }}
        environment: non-prod
      secrets: inherit