---
  name: network demo workflow 
  env:
    working_path: "demo/demo-account/network"
  on:
    workflow_dispatch:
    pull_request:
      paths:
        - demo/demo-account/network/**
    push:
      paths:
        - demo/demo-account/network/**
     
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
  jobs:
    preparation:
      name: preparation
      runs-on: ubuntu-latest
      outputs: 
        changes: ${{ steps.filter.outputs.changes }}
        working_path: ${{env.working_path}}
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Change filter
          uses: dorny/paths-filter@v2
          id: filter
          with:
             filters: |
                vpc:
                  - "${{env.working_path}}/vpc/**"
                security-group:
                  - "${{env.working_path}}/security-group/**"

    stage:
      needs: preparation
      uses: ./.github/workflows/reusable-terraform-workflow.yaml
      strategy:
        matrix: 
          subdirectories: ${{ fromJson(needs.preparation.outputs.changes) }}
        max-parallel: 1
      with:
        path: "${{needs.preparation.outputs.working_path}}/${{ matrix.subdirectories }}"
        environment: non-prod
      secrets: inherit