---
  name: resources demo workflow 
  env:
    working_path: "demo/demo-account/demo-application"
  on:
    workflow_dispatch:
    pull_request:
      paths:
        - demo/demo-account/demo-application/**
    push:
      paths:
        - demo/demo-account/demo-application/**
     
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
  jobs:
    preparation:
      name: preparation
      runs-on: ubuntu-latest
      outputs: 
        changes: ${{ steps.filter.outputs.changes }}
        working_path: ${{env.working_path}}
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Change filter
          uses: dorny/paths-filter@v2
          id: filter
          with:
             filters: |
                ec2:
                  - "${{env.working_path}}/ec2/**"
                ebs:
                  - "${{env.working_path}}/ebs/**"
                rds:
                  - "${{env.working_path}}/rds/**"
                elb:
                  - "${{env.working_path}}/elb/**"
                sns:
                  - "${{env.working_path}}/sns/**"
                sqs:
                  - "${{env.working_path}}/sqs/**"
                fsx:
                  - "${{env.working_path}}/fsx/**"

    stage:
      needs: preparation
      uses: ./.github/workflows/reusable-terraform-workflow.yaml
      strategy:
        fail-fast: false
        matrix: 
          subdirectories: ${{ fromJson(needs.preparation.outputs.changes) }}
        max-parallel: 1
      with:
        path: "${{needs.preparation.outputs.working_path}}/${{ matrix.subdirectories }}"
        environment: non-prod
      secrets: inherit
      