---
  name: demo workflow 
  on:
    workflow_dispatch:
    pull_request:
      paths:
        - demo/demo-account/demo-application/*
        - demo/demo-account/demo-application/config/* 
        - .github/workflows/terraform-demo.yml
    push:
      paths:
        - demo/demo-account/demo-application/*
        - demo/demo-account/demo-application/config/* 
        - .github/workflows/terraform-demo.yml
     
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
  jobs:
    call-workflow-passing-data:
      uses: ./.github/workflows/terraform-workflow.yaml
      with:
        path: demo/demo-account/demo-application/
        environment: non-prod
      secrets: inherit