---
  name: demo workflow 
  on:
    workflow_dispatch:
    pull_request:
      paths:
        - demo/demo-account/demo-application/**
        - .github/workflows/terraform-demo.yml
    push:
      paths:
        - demo/demo-account/demo-application/**
        - .github/workflows/terraform-demo.yml
     
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    
  jobs:
    drift-detection:
      name: drift-detection
      runs-on: ubuntu-latest
      outputs: 
        network: ${{ steps.filter.outputs.network }}
        resources: ${{ steps.filter.outputs.resources }}
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Change filter
          uses: dorny/paths-filter@v2
          id: filter
          with:
             filters: |
                network:
                  - 'demo/demo-account/demo-application/network/**'
                resources:
                  - 'demo/demo-account/demo-application/resources/**'
    terraform-network:
      needs: drift-detection
      if: ${{ needs.drift-detection.outputs.network }} == 'true'
      uses: ./.github/workflows/reusable-terraform-workflow.yaml
      with:
        path: demo/demo-account/demo-application/network
        environment: non-prod
      secrets: inherit
    terraform-resources:
      needs: 
        - drift-detection
        - terraform-network
      if: ${{ needs.drift-detection.outputs.resources }} == 'true'
      uses: ./.github/workflows/reusable-terraform-workflow.yaml
      with:
        path: demo/demo-account/demo-application/resources
        environment: non-prod
      secrets: inherit